In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
import os 
os.chdir("C:/Users/arman/ostad_code")

In [2]:
df=pd.read_csv("insurance_data.csv")
df

    age  bought_insurance
0    22                 0
1    25                 0
2    47                 1
3    52                 0
4    46                 1
5    56                 1
6    55                 0
7    60                 1
8    62                 1
9    61                 1
10   18                 0
11   28                 0
12   27                 0
13   29                 0
14   49                 1
15   55                 1
16   25                 1
17   58                 1
18   19                 0
19   18                 0
20   21                 0
21   26                 0
22   40                 1
23   45                 1
24   50                 1
25   54                 1
26   23                 0

In [3]:
x=df[['age']]

In [4]:
x

    age
0    22
1    25
2    47
3    52
4    46
5    56
6    55
7    60
8    62
9    61
10   18
11   28
12   27
13   29
14   49
15   55
16   25
17   58
18   19
19   18
20   21
21   26
22   40
23   45
24   50
25   54
26   23

In [6]:
y=df[["bought_insurance"]]
y

    bought_insurance
0                  0
1                  0
2                  1
3                  0
4                  1
5                  1
6                  0
7                  1
8                  1
9                  1
10                 0
11                 0
12                 0
13                 0
14                 1
15                 1
16                 1
17                 1
18                 0
19                 0
20                 0
21                 0
22                 1
23                 1
24                 1
25                 1
26                 0

In [8]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)

In [9]:
x_train

    age
13   29
2    47
1    25
23   45
14   49
4    46
22   40
6    55
7    60
5    56
20   21
9    61
11   28
26   23
19   18
21   26
0    22
8    62
3    52
24   50
10   18

In [10]:
x_test

    age
18   19
17   58
12   27
25   54
15   55
16   25

In [14]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

C:\Users\arman\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [17]:
y_test

    bought_insurance
18                 0
17                 1
12                 0
25                 1
15                 1
16                 1

In [16]:
model.score(x_test,y_test)

0.8333333333333334

In [23]:
model.predict([[25]])

C:\Users\arman\AppData\Local\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [25]:
model.predict(x_test)

array([0, 1, 0, 1, 1, 0])