In [31]:
import numpy as np
import pandas as pd

In [32]:
import os
os.chdir("C:/Users/arman/ostad_code")

In [33]:
df=pd.read_csv("ham_spam.csv")
df

     Category                                            Message
0         ham  Go until jurong point, crazy.. Available only ...
1         ham                      Ok lar... Joking wif u oni...
2        spam  Free entry in 2 a wkly comp to win FA Cup fina...
3         ham  U dun say so early hor... U c already then say...
4         ham  Nah I don't think he goes to usf, he lives aro...
...       ...                                                ...
5567     spam  This is the 2nd time we have tried 2 contact u...
5568      ham               Will ü b going to esplanade fr home?
5569      ham  Pity, * was in mood for that. So...any other s...
5570      ham  The guy did some bitching but I acted like i'd...
5571      ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [34]:
df.Category.value_counts() #category columns ar modde kon value koto ta ase tai daksi

Category
ham     4825
spam     747
Name: count, dtype: int64

In [35]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.Message,df.Category,test_size=0.2,random_state=5)

In [36]:
x_test

2095    PRIVATE! Your 2004 Account Statement for 07742...
5343    No go. No openings for that room 'til after th...
564     GENT! We are trying to contact you. Last weeke...
3849    Can you plz tell me the ans. BSLVYL sent via f...
3317    I know girls always safe and selfish know i go...
                              ...
3473    I think I‘m waiting for the same bus! Inform m...
884                           Dude we should go sup again
5006    Guess which pub im in? Im as happy as a pig in...
3397    URGENT! Your Mobile number has been awarded wi...
1309       I jokin oni lar.. Ü busy then i wun disturb ü.
Name: Message, Length: 1115, dtype: object

In [37]:
y_test

2095    spam
5343     ham
564     spam
3849     ham
3317     ham
        ...
3473     ham
884      ham
5006     ham
3397    spam
1309     ham
Name: Category, Length: 1115, dtype: object

In [38]:
x_train

1658    S:-)if we have one good partnership going we w...
1509    Sounds like something that someone testing me ...
3266    44 7732584351, Do you want a New Nokia 3510i c...
5199           Ugh my leg hurts. Musta overdid it on mon.
3217    URGENT! We are trying to contact U. Todays dra...
                              ...
3046    Hello, yeah i've just got out of the bath and ...
1725              There bold 2  &lt;#&gt; . Is that yours
4079                  Gam gone after outstanding innings.
2254                         Lol enjoy role playing much?
2915    Sorry! U can not unsubscribe yet. THE MOB offe...
Name: Message, Length: 4457, dtype: object

In [39]:
y_train

1658     ham
1509     ham
3266    spam
5199     ham
3217    spam
        ...
3046     ham
1725     ham
4079     ham
2254     ham
2915    spam
Name: Category, Length: 4457, dtype: object

In [40]:
type(x_train)

pandas.core.series.Series

In [41]:
x_train.shape

(4457,)

# akn amra bag of world create korbo count vectorizer ar maddome,,

In [42]:
#model to text sonkha bujbe na tai amader bag of world ar maddome sonkai rupantor korte hbe text k,,scalling ar moto

In [43]:
from sklearn.feature_extraction.text import CountVectorizer
v=CountVectorizer()

In [44]:
emails=[
            "upto 20% discount reward! upto",
            "hey Arman, discount upto"
        ]

In [45]:
type(emails)

list

In [46]:
emails

['upto 20% discount reward! upto', 'hey Arman, discount upto']

In [47]:
emails_cv=v.fit_transform(emails)
emails_cv

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 8 stored elements and shape (2, 6)>

In [48]:
nj=emails_cv.toarray()
nj
#toarray() ar maddome output ta dekhte hbe,,variable ar pore toarray() jog korte hbe

array([[1, 0, 1, 0, 1, 2],
       [0, 1, 1, 1, 0, 1]])

In [49]:
hj=v.get_feature_names_out()
hj
#get_feature_names_out() ar maddome unique feature gula dekhabe

array(['20', 'arman', 'discount', 'hey', 'reward', 'upto'], dtype=object)

In [50]:
df=pd.DataFrame(data=nj,columns=hj)
df

   20  arman  discount  hey  reward  upto
0   1      0         1    0       1     2
1   0      1         1    1       0     1

In [51]:
emails

['upto 20% discount reward! upto', 'hey Arman, discount upto']

In [52]:
v=CountVectorizer()
x_train_cv=v.fit_transform(x_train)
x_train_cv
#bag of words korlam

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 59063 stored elements and shape (4457, 7705)>

In [53]:
x_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [54]:
x_train_cv.toarray().shape

(4457, 7705)

In [55]:
x_train_cv.shape
#4457 ta sentense a 7705 ta unique word ase

(4457, 7705)

In [56]:
v.get_feature_names_out()

array(['00', '000', '000pes', ..., 'zouk', 'èn', '〨ud'], dtype=object)

In [57]:
new_df=pd.DataFrame(data=x_train_cv.toarray(),columns=v.get_feature_names_out())
new_df

,00,000,000pes,008704050406,0089,01223585236,01223585334,0125698789,02,0207,...,yup,yupz,zaher,zed,zhong,zoe,zoom,zouk,èn,〨ud
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4452,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4453,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4454,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4455,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4456,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [58]:
new_df.shape

(4457, 7705)

In [59]:
pd.set_option("display.max_columns",None)
new_df

      00  000  000pes  008704050406  0089  01223585236  01223585334  \
0      0    0       0             0     0            0            0
1      0    0       0             0     0            0            0
2      0    0       0             0     0            0            0
3      0    0       0             0     0            0            0
4      0    0       0             0     0            0            0
...   ..  ...     ...           ...   ...          ...          ...
4452   0    0       0             0     0            0            0
4453   0    0       0             0     0            0            0
4454   0    0       0             0     0            0            0
4455   0    0       0             0     0            0            0
4456   0    0       0             0     0            0            0

      0125698789  02  0207  02072069400  02073162414  02085076972  021  03  \
0              0   0     0            0            0            0    0   0
1              0   0     0            0            0            0    0   0
2              0   0     0            0            0            0    0   0
3              0   0     0            0            0            0    0   0
4              0   0     0            0            0            0    0   0
...          ...  ..   ...          ...          ...          ...  ...  ..
4452           0   0     0            0            0            0    0   0
4453           0   0     0            0            0            0    0   0
4454           0   0     0            0            0            0    0   0
4455           0   0     0            0            0            0    0   0
4456           0   0     0            0            0            0    0   0

      04  0430  05  050703  0578  06  07  07046744435  07090201529  \
0      0     0   0       0     0   0   0            0            0
1      0     0   0       0     0   0   0            0            0
2      0     0   0       0     0   0   0            0            0
3      0     0   0       0     0   0   0            0            0
4      0     0   0       0     0   0   0            0            0
...   ..   ...  ..     ...   ...  ..  ..          ...          ...
4452   0     0   0       0     0   0   0            0            0
4453   0     0   0       0     0   0   0            0            0
4454   0     0   0       0     0   0   0            0            0
4455   0     0   0       0     0   0   0            0            0
4456   0     0   0       0     0   0   0            0            0

      07090298926  07123456789  0721072  07732584351  07734396839  \
0               0            0        0            0            0
1               0            0        0            0            0
2               0            0        0            0            0
3               0            0        0            0            0
4               0            0        0            0            0
...           ...          ...      ...          ...          ...
4452            0            0        0            0            0
4453            0            0        0            0            0
4454            0            0        0            0            0
4455            0            0        0            0            0
4456            0            0        0            0            0

      07742676969  07753741225  0776xxxxxxx  07781482378  07786200117  077xxx  \
0               0            0            0            0            0       0
1               0            0            0            0            0       0
2               0            0            0            0            0       0
3               0            0            0            0            0       0
4               0            0            0            0            0       0
...           ...          ...          ...          ...          ...     ...
4452            0            0            0            0            0       0
4453            0            0            0            0            0       0
4454            0            0            0            0            0       0
4455            0            0            0            0            0       0
4456            0            0            0            0            0       0

      078  07801543489  07808  07808247860  07808726822  07815296484  \
0       0            0      0            0            0            0
1       0            0      0            0            0            0
2       0            0      0            0            0            0
3       0            0      0            0            0            0
4       0            0      0            0            0            0
...   ...          ...    ...          ...          ...          ...
4452    0            0      0            0            0            0
4453    0            0      0            0            0            0
4454    0            0      0            0            0            0
4455    0            0      0            0            0            0
4456    0            0      0            0            0            0

      07821230901  078498  07880867867  0789xxxxxxx  07946746291  07973788240  \
0               0       0            0            0            0            0
1               0       0            0            0            0            0
2               0       0            0            0            0            0
3               0       0            0            0            0            0
4               0       0            0            0            0            0
...           ...     ...          ...          ...          ...          ...
4452            0       0            0            0            0            0
4453            0       0            0            0            0            0
4454            0       0            0            0            0            0
4455            0       0            0            0            0            0
4456            0       0            0            0            0            0

      07xxxxxxxxx  08  0800  08000407165  08000776320  08000839402  \
0               0   0     0            0            0            0
1               0   0     0            0            0            0
2               0   0     0            0            0            0
3               0   0     0            0            0            0
4               0   0     0            0            0            0
...           ...  ..   ...          ...          ...          ...
4452            0   0     0            0            0            0
4453            0   0     0            0            0            0
4454            0   0     0            0            0            0
4455            0   0     0            0            0            0
4456            0   0     0            0            0            0

      08000930705  08000938767  08001950382  08002888812  08002986030  \
0               0            0            0            0            0
1               0            0            0            0            0
2               1            0            0            0            0
3               0            0            0            0            0
4               0            0            0            0            0
...           ...          ...          ...          ...          ...
4452            0            0            0            0            0
4453            0            0            0            0            0
4454            0            0            0            0            0
4455            0            0            0            0            0
4456            0            0            0            0            0

      08002986906  08002988890  08006344447  0808  08081263000  08081560665  \
0               0            0            0     0            0            0
1               0            0            0     0            0            0
2               0            0            0     0            0            0
3               0            0            0     0            0            0
4               0            0            0     0            0            0
...           ...          ...          ...   ...          ...          ...
4452            0            0            0     0            0            0
4453            0            0            0     0            0            0
4454            0            0            0     0            0            0
4455            0            0            0     0            0            0
4456            0            0            0     0            0            0

      0825  0844  08448350055  08448714184  0845  08450542832  08452810071  \
0        0     0            0            0     0            0            0
1        0     0            0            0     0            0            0
2        0     0            0            0     0            0            0
3        0     0            0            0     0            0            0
4        0     0            0            0     0            0            0
...    ...   ...          ...          ...   ...          ...          ...
4452     0     0            0            0     0            0            0
4453     0     0            0            0     0            0            0
4454     0     0            0            0     0            0            0
4455     0     0            0            0     0            0            0
4456     0     0            0            0     0            0            0

      08452810073  08452810075over18  0870  08700435505150p  08700469649  \
0               0                  0     0                0            0
1               0                  0     0                0            0
2               0                  0     0                0            0
3               0                  0     0                0            0
4               0                  0     0                0            0
...           ...                ...   ...              ...          ...
4452            0                  0     0                0            0
4453            0                  0     0                0            0
4454            0                  0     0                0            0
4455            0                  0     0                0            0
4456            0                  0     0                0            0

      08700621170150p  08701213186  08701417012  0870141701216  087016248  \
0                   0            0            0              0          0
1                   0            0            0              0          0
2                   0            0            0              0          0
3                   0            0            0              0          0
4                   0            0            0              0          0
...               ...          ...          ...            ...        ...
4452                0            0            0              0          0
4453                0            0            0              0          0
4454                0            0            0              0          0
4455                0            0            0              0          0
4456                0            0            0              0          0

      08701752560  0870241182716  08702490080  08702840625  08704050406  \
0               0              0            0            0            0
1               0              0            0            0            0
2               0              0            0            0            0
3               0              0            0            0            0
4               0              0            0            0            0
...           ...            ...          ...          ...          ...
4452            0              0            0            0            0
4453            0              0            0            0            0
4454            0              0            0            0            0
4455            0              0            0            0            0
4456            0              0            0            0            0

      08704439680  08704439680ts  08706091795  0870737910216yrs  08707500020  \
0               0              0            0                 0            0
1               0              0            0                 0            0
2               0              0            0                 0            0
3               0              0            0                 0            0
4               0              0            0                 0            0
...           ...            ...          ...               ...          ...
4452            0              0            0                 0            0
4453            0              0            0                 0            0
4454            0              0            0                 0            0
4455            0              0            0                 0            0
4456            0              0            0                 0            0

      08707509020  0870753331018  08707808226  08708034412  08708800282  \
0               0              0            0            0            0
1               0              0            0            0            0
2               0              0            0            0            0
3               0              0            0            0            0
4               0              0            0            0            0
...           ...            ...          ...          ...          ...
4452            0              0            0            0            0
4453            0              0            0            0            0
4454            0              0            0            0            0
4455            0              0            0            0            0
4456            0              0            0            0            0

      08709222922  0871  087104711148  08712101358  08712103738  \
0               0     0             0            0            0
1               0     0             0            0            0
2               0     0             0            0            0
3               0     0             0            0            0
4               0     0             0            0            0
...           ...   ...           ...          ...          ...
4452            0     0             0            0            0
4453            0     0             0            0            0
4454            0     0             0            0            0
4455            0     0             0            0            0
4456            0     0             0            0            0

      0871212025016  08712300220  087123002209am  08712317606  08712400200  \
0                 0            0               0            0            0
1                 0            0               0            0            0
2                 0            0               0            0            0
3                 0            0               0            0            0
4                 0            0               0            0            0
...             ...          ...             ...          ...          ...
4452              0            0               0            0            0
4453              0            0               0            0            0
4454              0            0               0            0            0
4455              0            0               0            0            0
4456              0            0               0            0            0

      08712400602450p  08712400603  08712402050  08712402578  08712402779  \
0                   0            0            0            0            0
1                   0            0            0            0            0
2                   0            0            0            0            0
3                   0            0            0            0            0
4                   0            0            0            0            0
...               ...          ...          ...          ...          ...
4452                0            0            0            0            0
4453                0            0            0            0            0
4454                0            0            0            0            0
4455                0            0            0            0            0
4456                0            0            0            0            0

      08712402902  08712402972  08712405020  08712460324  08712466669  \
0               0            0            0            0            0
1               0            0            0            0            0
2               0            0            0            0            0
3               0            0            0            0            0
4               0            0            0            0            0
...           ...          ...          ...          ...          ...
4452            0            0            0            0            0
4453            0            0            0            0            0
4454            0            0            0            0            0
4455            0            0            0            0            0
4456            0            0            0            0            0

      0871277810710p  0871277810810  0871277810910p  08714712379  08714712388  \
0                  0              0               0            0            0
1                  0              0               0            0            0
2                  0              0               0            0            0
3                  0              0               0            0            0
4                  0              0               0            0            0
...              ...            ...             ...          ...          ...
4452               0              0               0            0            0
4453               0              0               0            0            0
4454               0              0               0            0            0
4455               0              0               0            0            0
4456               0              0               0            0            0

      08714712394  08714712412  08714714011  08715203028  08715203649  \
0               0            0            0            0            0
1               0            0            0            0            0
2               0            0            0            0            0
3               0            0            0            0            0
4               0            0            0            0            0
...           ...          ...          ...          ...          ...
4452            0            0            0            0            0
4453            0            0            0            0            0
4454            0            0            0            0            0
4455            0            0            0            0            0
4456            0            0            0            0            0

      08715203652  08715203656  08715203677  08715203685  08715203694  \
0               0            0            0            0            0
1               0            0            0            0            0
2               0            0            0            0            0
3               0            0            0            0            0
4               0            0            0            0            0
...           ...          ...          ...          ...          ...
4452            0            0            0            0            0
4453            0            0            0            0            0
4454            0            0            0            0            0
4455            0            0            0            0            0
4456            0            0            0            0            0


In [60]:
from sklearn.naive_bayes import MultinomialNB
model=MultinomialNB()
model.fit(x_train_cv,y_train)

MultinomialNB()

In [61]:
x_test_cv=v.transform(x_test)
#ata aga decleard kora ase,tar modde x_test calaisi,karon ager 7000 column traning korano ase tar modde x test na calaile to model bujbe na

In [62]:
x_test_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [63]:
x_test_cv.shape

(1115, 7705)

In [64]:
model.score(x_test_cv,y_test)

0.9919282511210762

# confusion metrics

In [65]:
from sklearn.metrics import classification_report
y_pred=model.predict(x_test_cv)
print (classification_report(y_test,y_pred))

              precision    recall  f1-score   support

         ham       0.99      1.00      1.00       970
        spam       0.98      0.96      0.97       145

    accuracy                           0.99      1115
   macro avg       0.99      0.98      0.98      1115
weighted avg       0.99      0.99      0.99      1115

In [66]:
# amra nijeder banano sentense deye predect korbo akn,,sotik ans dai na ki

In [67]:
emails=[
    "hey jony,can we get together to watch cricket match?",
    "upto 30% discount on parking,exclusive offer just for you.Dont miss the reward"
]

In [68]:
emails_count=v.transform(emails)
emails_count.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [69]:
emails_count.toarray().shape

(2, 7705)

In [70]:
model.predict(emails_count.toarray())

array(['ham', 'spam'], dtype='<U4')

In [71]:
# yes right ans dese

In [72]:
#ata amra decission tree deye accuracy test korbo akn

In [73]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier()
dtree.fit(x_train_cv,y_train)

DecisionTreeClassifier()

In [74]:
dtree.score(x_test_cv,y_test)

0.9748878923766816